//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSG_Library.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point add_fasteners_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["add_fasteners_form_window_location"]));
            }
            set {
                this["add_fasteners_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point add_pierce_components_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["add_pierce_components_form_window_location"]));
            }
            set {
                this["add_pierce_components_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point assembly_auto_detail_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["assembly_auto_detail_form_window_location"]));
            }
            set {
                this["assembly_auto_detail_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point assembly_color_code_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["assembly_color_code_form_window_location"]));
            }
            set {
                this["assembly_color_code_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point assembly_export_design_data_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["assembly_export_design_data_form_window_location"]));
            }
            set {
                this["assembly_export_design_data_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point assembly_wave_link_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["assembly_wave_link_form_window_location"]));
            }
            set {
                this["assembly_wave_link_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point bill_of_material_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["bill_of_material_form_window_location"]));
            }
            set {
                this["bill_of_material_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point blank_data_builder_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["blank_data_builder_form_window_location"]));
            }
            set {
                this["blank_data_builder_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point block_attributer_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["block_attributer_form_window_location"]));
            }
            set {
                this["block_attributer_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point check_box_dialog_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["check_box_dialog_form_window_location"]));
            }
            set {
                this["check_box_dialog_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point clone_assembly_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["clone_assembly_form_window_location"]));
            }
            set {
                this["clone_assembly_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point clone_strip_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["clone_strip_form_window_location"]));
            }
            set {
                this["clone_strip_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point component_builder_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["component_builder_form_window_location"]));
            }
            set {
                this["component_builder_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point copy_attributes_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["copy_attributes_form_window_location"]));
            }
            set {
                this["copy_attributes_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point create_burnout_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["create_burnout_form_window_location"]));
            }
            set {
                this["create_burnout_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point cycle_components_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["cycle_components_form_window_location"]));
            }
            set {
                this["cycle_components_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point edit_block_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["edit_block_form_window_location"]));
            }
            set {
                this["edit_block_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point edit_size__form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["edit_size__form_window_location"]));
            }
            set {
                this["edit_size__form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point export_sim_package_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["export_sim_package_form_window_location"]));
            }
            set {
                this["export_sim_package_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point export_strip_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["export_strip_form_window_location"]));
            }
            set {
                this["export_strip_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point f_shape_exporter_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["f_shape_exporter_form_window_location"]));
            }
            set {
                this["f_shape_exporter_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point grid_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["grid_form_window_location"]));
            }
            set {
                this["grid_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point profile_trim_and_form_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["profile_trim_and_form_form_window_location"]));
            }
            set {
                this["profile_trim_and_form_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point proposal_data_wizard_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["proposal_data_wizard_form_window_location"]));
            }
            set {
                this["proposal_data_wizard_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ref_set_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["ref_set_form_window_location"]));
            }
            set {
                this["ref_set_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point session_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["session_form_window_location"]));
            }
            set {
                this["session_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point sim_ref_sets_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["sim_ref_sets_form_window_location"]));
            }
            set {
                this["sim_ref_sets_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point simulation_data_builder_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["simulation_data_builder_form_window_location"]));
            }
            set {
                this["simulation_data_builder_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point wire_start_hole_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["wire_start_hole_form_window_location"]));
            }
            set {
                this["wire_start_hole_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point wire_taper_development_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["wire_taper_development_form_window_location"]));
            }
            set {
                this["wire_taper_development_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreferredSetting {
            get {
                return ((bool)(this["PreferredSetting"]));
            }
            set {
                this["PreferredSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckGrid {
            get {
                return ((bool)(this["CheckGrid"]));
            }
            set {
                this["CheckGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GridIndex {
            get {
                return ((int)(this["GridIndex"]));
            }
            set {
                this["GridIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point detail_number_note_form_window_location {
            get {
                return ((global::System.Drawing.Point)(this["detail_number_note_form_window_location"]));
            }
            set {
                this["detail_number_note_form_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AssemblyColorCodeLastUsed {
            get {
                return ((int)(this["AssemblyColorCodeLastUsed"]));
            }
            set {
                this["AssemblyColorCodeLastUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AssemblyColorCodeWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["AssemblyColorCodeWindowLocation"]));
            }
            set {
                this["AssemblyColorCodeWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string component_builder_grid_increment {
            get {
                return ((string)(this["component_builder_grid_increment"]));
            }
            set {
                this["component_builder_grid_increment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point mirror_components_window_location {
            get {
                return ((global::System.Drawing.Point)(this["mirror_components_window_location"]));
            }
            set {
                this["mirror_components_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string EditBlockFormGridIncrement {
            get {
                return ((string)(this["EditBlockFormGridIncrement"]));
            }
            set {
                this["EditBlockFormGridIncrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int add_fasteners_preferred_index {
            get {
                return ((int)(this["add_fasteners_preferred_index"]));
            }
            set {
                this["add_fasteners_preferred_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool add_fasteners_cycle_add {
            get {
                return ((bool)(this["add_fasteners_cycle_add"]));
            }
            set {
                this["add_fasteners_cycle_add"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool add_fasteners_reverse_cycle_add {
            get {
                return ((bool)(this["add_fasteners_reverse_cycle_add"]));
            }
            set {
                this["add_fasteners_reverse_cycle_add"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int add_fasteners_grid_index {
            get {
                return ((int)(this["add_fasteners_grid_index"]));
            }
            set {
                this["add_fasteners_grid_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool add_fasteners_show_grid {
            get {
                return ((bool)(this["add_fasteners_show_grid"]));
            }
            set {
                this["add_fasteners_show_grid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point udoComponentBuilderWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["udoComponentBuilderWindowLocation"]));
            }
            set {
                this["udoComponentBuilderWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string udoComponentBuilderGridIncrement {
            get {
                return ((string)(this["udoComponentBuilderGridIncrement"]));
            }
            set {
                this["udoComponentBuilderGridIncrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point assembly_navigator_window_location {
            get {
                return ((global::System.Drawing.Point)(this["assembly_navigator_window_location"]));
            }
            set {
                this["assembly_navigator_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point blank_data_builder_window_location {
            get {
                return ((global::System.Drawing.Point)(this["blank_data_builder_window_location"]));
            }
            set {
                this["blank_data_builder_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point design_check_window_location {
            get {
                return ((global::System.Drawing.Point)(this["design_check_window_location"]));
            }
            set {
                this["design_check_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool comp_builder_4_digits {
            get {
                return ((bool)(this["comp_builder_4_digits"]));
            }
            set {
                this["comp_builder_4_digits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool com_builder_any_assembly {
            get {
                return ((bool)(this["com_builder_any_assembly"]));
            }
            set {
                this["com_builder_any_assembly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point create_reset_datum_csys_location {
            get {
                return ((global::System.Drawing.Point)(this["create_reset_datum_csys_location"]));
            }
            set {
                this["create_reset_datum_csys_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point simplify_curves_window_location {
            get {
                return ((global::System.Drawing.Point)(this["simplify_curves_window_location"]));
            }
            set {
                this["simplify_curves_window_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point plot_detail_drawings_location {
            get {
                return ((global::System.Drawing.Point)(this["plot_detail_drawings_location"]));
            }
            set {
                this["plot_detail_drawings_location"] = value;
            }
        }
    }
}
